config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  devise_for :installs

  resources :posts do 
    resources:comments
  end 

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create 
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save
		
		if @comment.save
			redirect_to post_path(@post)
		else 
			render 'new'
		end		
	end		

	def edit
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
	end

	def update 
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else 	
			render 'edit'
		end
	end

	def destroy 
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :is_owner, only: [:edit, :destroy]
	
	# before_filter :authenticate_user!, except: [:vote, :show_vote]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(parameters)
		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end


	def show
		find_post
	end

	def destroy
		find_post
		@post.destroy
		redirect_to root_path
	end

	def update
		find_post
		if @post.update(parameters)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def edit
		find_post
	end

	private
	def parameters
		params.require(:post).permit(:title, :content, :image)
	end

	def find_post
		@post = Post.find(params[:id])
	end

	def is_owner
		find_post
		if @post.user != current_user
			redirect_to @post
		end
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.content
		%p.comment_content= comment.comment
		%p.comment_author= "Feito por: " + comment.user.nickname
	.buttons
		= link_to "Editar", edit_post_comment_path(comment.post, comment)
		= link_to "Excluir", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build])  do |f|

	=f.input :comment
	=f.submit

app/views/comments/edit.html.haml
%h1 Edit Reply

= simple_form_for([@post, @comment]) do |f|
	= f.input :comment
	= f.submit

app/views/layouts/application.html.haml
!!!
%html
%head
	%title PROGama
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	%link{href:'http://fonts.googleapis.com/css?family=Ubuntu+Condensed', rel: 'stylesheet', type: 'text/css'}
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= favicon_link_tag
	= csrf_meta_tags
%body
	%p.barra_superior
		=link_to "Home", root_path
		|
		- if user_signed_in?
			=link_to "Editar conta", edit_user_registration_path
			|
			=link_to "Sair", destroy_user_session_path, method: :delete
			|
			Você está logado como: 
			=current_user.nickname
		- else
			=link_to "Registrar", new_user_registration_path
			|
			=link_to "Entrar", new_user_session_path
			
	.newtop
		%p PROGama Forum
		.patrocionio=image_tag asset_path('gama.jpg')

	.container
		%p.notice= notice
		%p.alert= alert
	.container
		=yield

app/views/posts/_newpost.html.haml
= simple_form_for @post, { multipart: true } do |p|
	Adicionar uma imagem
	%br
	%br
	= p.file_field :image
	%p
	= p.label :title, "Titulo"
	%p
	= p.text_field :title, class: "posts_text"
	%p
	= p.label :content, "Conteúdo"
	%p
	= p.text_area :content, class: "class_conteudo"
	%p
	= p.submit

app/views/posts/edit.html.haml
%h2 
	Editar "
	= @post.title
	"

= render 'newpost'
%p
= link_to "Cancelar", post_path

app/views/posts/index.html.haml
-if user_signed_in?
	%h1.new_post_btn=link_to "Novo post", new_post_path, class: "novoPostText"

- @posts.each do |p|
	.borda
		%h2.postlink= link_to p.title, p, class: "posts_text"
		%p.inform
			=time_ago_in_words(p.created_at)
			ago by
			= p.user.nickname
	%br

app/views/posts/new.html.haml
%h1 Nova postagem
%p
= render 'newpost'

app/views/posts/show.html.haml
#content
.borda
	%h1= @post.title
	
	%p.inform
		Criado por
		= @post.user.nickname
		em
		=@post.created_at.day 
		&#47
		=@post.created_at.month
		&#47
		=@post.created_at.year
		%p= @post.content
		-if @post.image.url(:large) != "/images/large/missing.png"
			= image_tag @post.image.url(:large)


#decisao
	-if @post.user == current_user

		%br/

		= link_to "Editar", edit_post_path(@post), class: "button"
		|
		= link_to "Excluir", post_path(@post), method: :delete, data: { confirm: "Tem certeza que deseja excluir este post?"}, class: "button"

#comments
	%h2= @post.comments.count.to_s + " comentario(s)"
	= render @post.comments

	%br/

	%h3 Responda ao Forum
	= render "comments/form"

	

	